# numpy库

In [ ]:
import numpy as np

# 系数矩阵 A
A = np.array([[1, 2], [3, 4], [5, 6]])

# 观测值向量 b
b = np.array([5, 6, 7])

# 使用最小二乘法求解线性方程组，只关心解向量 x
x = np.linalg.lstsq(A, b, rcond=None)[0]

print("解向量 x:", x)


In [ ]:
# 三角函数
import numpy as np
 
a = np.array([0,30,45,60,90])
print ('不同角度的正弦值：')
# 通过乘 pi/180 转化为弧度  
print (np.sin(a*np.pi/180))
print ('\n')
print ('数组中角度的余弦值：')
print (np.cos(a*np.pi/180))
print ('\n')
print ('数组中角度的正切值：')
print (np.tan(a*np.pi/180))


In [ ]:
# 反三角函数
import numpy as np
 
a = np.array([0,30,45,60,90])  
print ('含有正弦值的数组：')
sin = np.sin(a*np.pi/180)  
print (sin)
print ('\n')
print ('计算角度的反正弦，返回值以弧度为单位：')
inv = np.arcsin(sin)  
print (inv)
print ('\n')
print ('通过转化为角度制来检查结果：')
print (np.degrees(inv))
print ('\n')
print ('arccos 和 arctan 函数行为类似：')
cos = np.cos(a*np.pi/180)  
print (cos)
print ('\n')
print ('反余弦：')
inv = np.arccos(cos)  
print (inv)
print ('\n')
print ('角度制单位：')
print (np.degrees(inv))
print ('\n')
print ('tan 函数：')
tan = np.tan(a*np.pi/180)  
print (tan)
print ('\n')
print ('反正切：')
inv = np.arctan(tan)  
print (inv)
print ('\n')
print ('角度制单位：')
print (np.degrees(inv))

In [ ]:
# 自然底数e
import numpy as np
np.e
# 底数为e的对数
np.log(np.e)

In [ ]:
# 其他底数
import numpy as np
# way1
def log(base,x):
    return np.log(x)/np.log(base)
# 调用函数,不用加np.前缀
log(2,8)

# way2
x = 2
np.log10(x)  #以10为底
np.log2(x)
np.log1p(x) # 等价于：np.log(x + 1)

# way3 调用math库
import math 
# 以3为底数2为指数
print(math.pow(3,2))


In [ ]:
import numpy as np
x = np.array([[1, 2, 3],
             [4, 5, 6]])
   
y = np.array([1, 2, 3])

y_1 = np.array([[1],
                [2],
                [3]])
# dot()矩阵相乘/点乘
print(np.dot(x, y))

print(np.dot(x, y_1))

In [ ]:
import numpy as np
from numpy.linalg import pinv,eig, det
x = np.array([[1, -2, 1],
              [-2, 1, 1],
              [1, 1, -2]]) 
trans = x.T
# [[1 4 7]
#  [2 5 8]
#  [3 6 9]]
inverse = pinv(x)

determinant = det(x)

eigen_value, eigen_vector = eig(x)

print(eigen_value)

In [ ]:
# 举例
import numpy as np
A = np.array([[2,5],
              [1,3]])
value, vector = np.linalg.eig(A)

print(np.linalg.inv(A))
print(value)
print(vector)

## np.split(a,b,axis=)

In [ ]:
import numpy as np

# 创建一个一维数组
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 将数组拆分为3个子数组np.array型
split_arr = np.split(arr, 3)

# 打印拆分后的子数组
for sub_arr in split_arr:
    print(sub_arr)
print(split_arr)

In [ ]:
# 不均匀拆分
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# 拆分依据数字结尾
split_arr = np.split(arr, [3, 5])

for sub_arr in split_arr:
    print(sub_arr)

In [ ]:
# 按轴拆分
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_arr_2d = np.split(arr_2d, 2, axis=1)

for sub_arr in split_arr_2d:
    print(sub_arr)


In [ ]:
# 实例
import numpy as np

# 创建一个包含多个样本的一维数组
samples = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# 将样本重塑为二维数组，每个样本一行
samples_2d = samples.reshape(-1, 3)

# 将样本拆分为训练集和测试集
train_size = int(0.8 * len(samples_2d))
test_size = len(samples_2d) - train_size
train_samples, test_samples = np.split(samples_2d, [train_size, test_size])

print("训练集：")
print(train_samples)

print("\n测试集：")
print(test_samples)


In [ ]:
import numpy as np
A=np.array([[1,-2,1],
            [-2,1,1],
            [1,1,-2]])
eigen_value,eigen_vector = np.linalg.eig(A)
print(eigen_value)